export { default as IcBars } from "./icBars"
export { default as IcClose } from "./icClose"
export { default as IcEmail } from "./icEmail"
export { default as IcFacebook } from "./icFacebook"
export { default as IcInstagram } from "./icInstagram"
export { default as IcPersonal } from "./icPersonal"
export { default as IcExperience } from "./icExperience"
export { default as IcFacility } from "./icFacility"